# Generated by Django 2.2.1 on 2019-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=30)),
                ('ureceiver', models.CharField(max_length=20)),
                ('uaddress', models.CharField(max_length=100)),
                ('upostcode', models.CharField(max_length=6)),
                ('uphone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
