# Generated by Django 2.2.3 on 2019-07-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tushu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpub_data',
            new_name='bpub_date',
        ),
    ]
