# Generated by Django 2.2.1 on 2019-07-24 03:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('tpic', models.ImageField(default=False, upload_to='df_goods')),
                ('ticon', models.ImageField(default=False, upload_to='df_goods')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'producttype',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pbrief', models.CharField(max_length=200)),
                ('ppic', models.ImageField(upload_to='df_goods')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pstock', models.IntegerField()),
                ('punit', models.CharField(max_length=20)),
                ('pclick', models.IntegerField()),
                ('precommend', models.BooleanField(default=False)),
                ('pcontent', tinymce.models.HTMLField()),
                ('isDelete', models.BooleanField(default=False)),
                ('ptype', models.ForeignKey(on_delete='CASCADE', to='df_goods.ProductType')),
            ],
        ),
    ]
