# Generated by Django 2.2.1 on 2019-07-24 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productinfo',
            table='productinfo',
        ),
    ]
