# Generated by Django 2.2.1 on 2019-07-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20190724_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': '商品分类信息', 'verbose_name_plural': '商品分类信息'},
        ),
    ]
