# Generated by Django 2.2.1 on 2019-07-24 04:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20190724_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='pbrief',
            field=models.CharField(max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pclick',
            field=models.IntegerField(verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pcontent',
            field=tinymce.models.HTMLField(verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pname',
            field=models.CharField(max_length=20, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ppic',
            field=models.ImageField(upload_to='df_goods', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='precommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pstock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ptype',
            field=models.ForeignKey(on_delete='CASCADE', to='df_goods.ProductType', verbose_name='所属类'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='punit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='ticon',
            field=models.ImageField(default=False, upload_to='df_goods', verbose_name='类别图标'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='tpic',
            field=models.ImageField(default=False, upload_to='df_goods', verbose_name='推荐图片'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='ttitle',
            field=models.CharField(max_length=20, verbose_name='类别'),
        ),
    ]
