# Generated by Django 2.2.1 on 2019-07-24 06:15

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20190724_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='pcontent',
            field=DjangoUeditor.models.UEditorField(verbose_name='商品详情'),
        ),
    ]
