# Generated by Django 2.2.1 on 2019-07-24 06:41

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0006_auto_20190724_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='pcontent',
            field=DjangoUeditor.models.UEditorField(blank=True, default='test', verbose_name='商品详情'),
        ),
    ]
