# Generated by Django 2.2.1 on 2019-07-24 09:50

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0007_auto_20190724_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='pcontent',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='商品详情'),
        ),
    ]
