# Generated by Django 2.2.1 on 2019-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0008_auto_20190724_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='pnew_recommend',
            field=models.BooleanField(default=False, verbose_name='新品推荐'),
        ),
    ]
