# Generated by Django 2.2.1 on 2019-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0002_auto_20190724_1108'),
        ('df_goods', '0009_productinfo_pnew_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order_pro_id', models.ForeignKey(on_delete='CASCADE', to='df_goods.ProductInfo')),
                ('order_user_id', models.ForeignKey(on_delete='CASCADE', to='df_user.UserInfo')),
            ],
        ),
    ]
